services:
  backend:
    ports: !override
      - "${API_PORT}:${API_PORT}"
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "10.50.0.7:5001/csam_ai_training/api:latest"
        - "10.50.0.7:5001/csam_ai_training/api:2.0.1"

  frontend:
    ports: !override
      - "${NGINX_PORT}:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "10.50.0.7:5001/csam_ai_training/app:latest"
        - "10.50.0.7:5001/csam_ai_training/app:2.0.1"
