x-defaults:
  service: &base
    init: true
    restart: always

services:
  api:
    <<: *base
    container_name: api
    ports:
      - ${API_PORT}
    volumes:
      - ./backend/data:/api/data
      - ./backend/conf:/api/conf
    environment:
      API_PORT: ${API_PORT}
      NGINX_PORT: ${NGINX_PORT}
      FASTAPI_ROOT: ${FASTAPI_ROOT}
      PC_NAME: ${PC_NAME}
      LOCAL_DB_PATH: ${LOCAL_DB_PATH}
      REALTIMEDB: ${REALTIMEDB}
      TABLEID_AUG: ${TABLEID_AUG}
      TABLEID_TRAIN: ${TABLEID_TRAIN}
      TABLEID_EVAL: ${TABLEID_EVAL}
  app:
    <<: *base
    container_name: app
    ports:
      - ${APP_PORT}
  nginx:
    <<: *base
    image: nginx
    container_name: nginx
    depends_on:
      - api
      - app
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - ${NGINX_PORT}:80
    environment:
      API_PORT: ${API_PORT}
      APP_PORT: ${APP_PORT}
