services:
  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: "10.50.0.7:5001/csam_ai_training/api:1.0.0"
    volumes:
      - ./backend/data:/api/data
      - ./backend/conf:/api/conf
    ports:
      - "8101"
    environment:
      CORS: ${CORS}
      PRASS_URL: ${PRASS_URL}
      LOT_COL: ${LOT_COL}
      ITEM_COL: ${ITEM_COL}
      ITEM: ${ITEM}
      REALTIMEDB: ${REALTIMEDB}
      TABLEID_AUG: ${TABLEID_AUG}
      TABLEID_TRAIN: ${TABLEID_TRAIN}
      TABLEID_EVAL: ${TABLEID_EVAL}
    # deploy:
    #   mode: replicated
    #   replicas: 3
  app:
    build:
      # context: ./frontend
      # dockerfile: Dockerfile
      # target: prod
    image: "10.50.0.7:5001/csam_ai_training/app:1.0.0"
    ports:
      - "3101"
    environment:
      REACT_APP_API: http://api.localhost
  nginx:
    depends_on:
      - api
    restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: ./nginx
    image: "10.50.0.7:5001/csam_ai_training/nginx:1.0.0"
    ports:
      - "80:80"
